# Mock db on localhost
# From backend root directory, run: docker-compose -f external/sql/mock_db/docker-compose.yml up
version: '0.1'

services:

  db:
    image: postgres:16.1-alpine
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 512mb
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: grabbootcamp
      POSTGRES_PASSWORD: verystrongpass2024
      POSTGRES_DB: grab_bootcamp
    ports:
      - "5432:5432"


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"